package com.example.interviewplatform.common.controller

import org.junit.jupiter.api.Test
import org.springframework.beans.factory.annotation.Autowired
import org.springframework.boot.test.autoconfigure.jdbc.AutoConfigureTestDatabase
import org.springframework.boot.test.autoconfigure.web.servlet.AutoConfigureMockMvc
import org.springframework.boot.test.context.SpringBootTest
import org.springframework.test.context.ActiveProfiles
import org.springframework.test.web.servlet.MockMvc
import org.springframework.test.web.servlet.request.MockMvcRequestBuilders.get
import org.springframework.test.web.servlet.result.MockMvcResultMatchers.jsonPath
import org.springframework.test.web.servlet.result.MockMvcResultMatchers.status
import org.testcontainers.junit.jupiter.Testcontainers

@SpringBootTest
@AutoConfigureMockMvc
@ActiveProfiles("test")
@AutoConfigureTestDatabase(replace = AutoConfigureTestDatabase.Replace.NONE)
@Testcontainers(disabledWithoutDocker = true)
class OpenApiIntegrationTest {
    @Autowired
    private lateinit var mockMvc: MockMvc

    @Test
    fun `openapi docs endpoint exposes implemented auth and protected paths`() {
        mockMvc.perform(get("/v3/api-docs"))
            .andExpect(status().isOk)
            .andExpect(jsonPath("$.openapi").exists())
            .andExpect(jsonPath("$.paths['/api/auth/login']").exists())
            .andExpect(jsonPath("$.paths['/api/me']").exists())
            .andExpect(jsonPath("$.paths['/api/me/profile-image']").exists())
            .andExpect(jsonPath("$.paths['/api/resumes/{resumeId}/versions/upload']").exists())
            .andExpect(jsonPath("$.paths['/api/resume-versions/{versionId}']").exists())
            .andExpect(jsonPath("$.paths['/api/resume-versions/{versionId}/extraction']").exists())
            .andExpect(jsonPath("$.paths['/api/resume-versions/{versionId}/file']").exists())
            .andExpect(jsonPath("$.paths['/api/resume-versions/{versionId}/profile']").exists())
            .andExpect(jsonPath("$.paths['/api/resume-versions/{versionId}/contacts']").exists())
            .andExpect(jsonPath("$.paths['/api/resume-versions/{versionId}/competencies']").exists())
            .andExpect(jsonPath("$.paths['/api/resume-versions/{versionId}/projects']").exists())
            .andExpect(jsonPath("$.paths['/api/resume-versions/{versionId}/achievements']").exists())
            .andExpect(jsonPath("$.paths['/api/resume-versions/{versionId}/education']").exists())
            .andExpect(jsonPath("$.paths['/api/resume-versions/{versionId}/certifications']").exists())
            .andExpect(jsonPath("$.paths['/api/resume-versions/{versionId}/awards']").exists())
            .andExpect(jsonPath("$.paths['/api/resume-versions/{versionId}/re-extract']").exists())
            .andExpect(jsonPath("$.paths['/api/questions/{questionId}/reference-answers']").exists())
            .andExpect(jsonPath("$.paths['/api/questions/{questionId}/learning-materials']").exists())
            .andExpect(jsonPath("$.paths['/api/archive']").exists())
            .andExpect(jsonPath("$.paths['/api/interview-sessions']").exists())
            .andExpect(jsonPath("$.paths['/api/interview-sessions/{sessionId}']").exists())
            .andExpect(jsonPath("$.paths['/api/interview-sessions/{sessionId}/coverage']").exists())
            .andExpect(jsonPath("$.paths['/api/interview-sessions/{sessionId}/resume-map']").exists())
            .andExpect(jsonPath("$.paths['/api/interview-sessions/{sessionId}/skip-question']").exists())
            .andExpect(jsonPath("$.paths['/api/interview-records']").exists())
            .andExpect(jsonPath("$.paths['/api/interview-records/{recordId}']").exists())
            .andExpect(jsonPath("$.paths['/api/interview-records/{recordId}/transcript']").exists())
            .andExpect(jsonPath("$.paths['/api/interview-records/{recordId}/transcript/segments/{segmentId}']").exists())
            .andExpect(jsonPath("$.paths['/api/interview-records/{recordId}/questions']").exists())
            .andExpect(jsonPath("$.paths['/api/interview-records/{recordId}/review']").exists())
            .andExpect(jsonPath("$.paths['/api/interview-records/{recordId}/review'].patch").exists())
            .andExpect(jsonPath("$.paths['/api/interview-records/{recordId}/analysis']").exists())
            .andExpect(jsonPath("$.paths['/api/interview-records/{recordId}/interviewer-profile']").exists())
            .andExpect(jsonPath("$.paths['/api/interview-records/{recordId}/confirm']").exists())
            .andExpect(jsonPath("$.paths['/api/home']").exists())
            .andExpect(jsonPath("$.components.schemas.CreateInterviewSessionRequest.properties.interviewMode").exists())
            .andExpect(jsonPath("$.components.schemas.CreateInterviewSessionRequest.properties.sourceInterviewRecordId").exists())
            .andExpect(jsonPath("$.components.schemas.CreateInterviewSessionRequest.properties.replayMode").exists())
            .andExpect(jsonPath("$.components.schemas.InterviewSessionQuestionDto.properties.bodyText").exists())
            .andExpect(jsonPath("$.components.schemas.InterviewSessionQuestionDto.properties.focusSkillNames").exists())
            .andExpect(jsonPath("$.components.schemas.InterviewSessionQuestionDto.properties.resumeEvidence").exists())
            .andExpect(jsonPath("$.components.schemas.InterviewSessionQuestionDto.properties.sourceType").exists())
            .andExpect(jsonPath("$.components.schemas.InterviewSessionQuestionDto.properties.generationStatus").exists())
            .andExpect(jsonPath("$.components.schemas.InterviewSessionSummaryDto.properties.skippedQuestions").exists())
            .andExpect(jsonPath("$.components.schemas.InterviewSessionDetailResponseDto.properties.sourceInterviewRecordId").exists())
            .andExpect(jsonPath("$.components.schemas.InterviewSessionDetailResponseDto.properties.replayMode").exists())
            .andExpect(jsonPath("$.components.schemas.QuestionDetailResponse.properties.practicalInterviewContext").exists())
            .andExpect(jsonPath("$.components.schemas.PracticalInterviewQuestionContextDto").exists())
            .andExpect(jsonPath("$.components.schemas.InterviewRecordQuestionDto.properties.linkedQuestionId").exists())
            .andExpect(jsonPath("$.components.schemas.InterviewRecordQuestionDto.properties.structuringSource").exists())
            .andExpect(jsonPath("$.components.schemas.InterviewRecordQuestionAnswerDto.properties.structuringSource").exists())
            .andExpect(jsonPath("$.components.schemas.InterviewRecordDetailDto.properties.structuringStage").exists())
            .andExpect(jsonPath("$.components.schemas.InterviewRecordDetailDto.properties.deterministicSummary").exists())
            .andExpect(jsonPath("$.components.schemas.InterviewRecordDetailDto.properties.aiEnrichedSummary").exists())
            .andExpect(jsonPath("$.components.schemas.InterviewRecordAnalysisDto.properties.structuringStage").exists())
            .andExpect(jsonPath("$.components.schemas.InterviewerProfileDto.properties.structuringSource").exists())
            .andExpect(jsonPath("$.components.schemas.InterviewRecordReviewDto").exists())
            .andExpect(jsonPath("$.components.schemas.InterviewRecordReviewDto.properties.editedSegmentCount").exists())
            .andExpect(jsonPath("$.components.schemas.InterviewRecordReviewDto.properties.changedQuestionCount").exists())
            .andExpect(jsonPath("$.components.schemas.InterviewRecordReviewDto.properties.questionFilterSummary").exists())
            .andExpect(jsonPath("$.components.schemas.InterviewRecordReviewDto.properties.questionDistributionSummary").exists())
            .andExpect(jsonPath("$.components.schemas.InterviewRecordReviewDto.properties.questionOriginSummary").exists())
            .andExpect(jsonPath("$.components.schemas.InterviewRecordReviewDto.properties.replayReadiness").exists())
            .andExpect(jsonPath("$.components.schemas.InterviewRecordReviewDto.properties.transcriptIssueSummary").exists())
            .andExpect(jsonPath("$.components.schemas.InterviewRecordReviewDto.properties.answerQualitySummary").exists())
            .andExpect(jsonPath("$.components.schemas.InterviewRecordReviewDto.properties.timelineNavigation").exists())
            .andExpect(jsonPath("$.components.schemas.InterviewRecordReviewDto.properties.actionRecommendations").exists())
            .andExpect(jsonPath("$.components.schemas.InterviewRecordReviewDto.properties.replayLaunchPreset").exists())
            .andExpect(jsonPath("$.components.schemas.InterviewRecordReviewDto.properties.provenanceComparisonSummary").exists())
            .andExpect(jsonPath("$.components.schemas.InterviewRecordReviewDto.properties.questionSummaries").exists())
            .andExpect(jsonPath("$.components.schemas.InterviewRecordReviewDto.properties.followUpThreads").exists())
            .andExpect(jsonPath("$.components.schemas.InterviewRecordReviewQuestionFilterSummaryDto").exists())
            .andExpect(jsonPath("$.components.schemas.InterviewRecordReviewQuestionDistributionSummaryDto").exists())
            .andExpect(jsonPath("$.components.schemas.InterviewRecordReviewQuestionOriginSummaryDto").exists())
            .andExpect(jsonPath("$.components.schemas.InterviewRecordReplayReadinessDto").exists())
            .andExpect(jsonPath("$.components.schemas.InterviewRecordTranscriptIssueSummaryDto").exists())
            .andExpect(jsonPath("$.components.schemas.InterviewRecordTranscriptSegmentActionDto").exists())
            .andExpect(jsonPath("$.components.schemas.InterviewRecordTranscriptSegmentActionDto.properties.deepLink").exists())
            .andExpect(jsonPath("$.components.schemas.InterviewRecordTranscriptSegmentActionDto.properties.replayLaunchPreset").exists())
            .andExpect(jsonPath("$.components.schemas.InterviewRecordAnswerQualitySummaryDto").exists())
            .andExpect(jsonPath("$.components.schemas.InterviewRecordTimelineNavigationDto").exists())
            .andExpect(jsonPath("$.components.schemas.InterviewRecordTimelineNavigationItemDto").exists())
            .andExpect(jsonPath("$.components.schemas.InterviewRecordReviewActionRecommendationsDto").exists())
            .andExpect(jsonPath("$.components.schemas.InterviewRecordReplayLaunchPresetDto").exists())
            .andExpect(jsonPath("$.components.schemas.InterviewRecordProvenanceComparisonSummaryDto").exists())
            .andExpect(jsonPath("$.components.schemas.InterviewRecordReviewQuestionSummaryDto").exists())
            .andExpect(jsonPath("$.components.schemas.InterviewRecordReviewQuestionDeepLinkDto").exists())
            .andExpect(jsonPath("$.components.schemas.InterviewRecordReviewFollowUpThreadDto").exists())
            .andExpect(jsonPath("$.components.schemas.BulkUpdateInterviewTranscriptSegmentsRequest").exists())
            .andExpect(jsonPath("$.components.schemas.InterviewSessionCoverageResponseDto").exists())
            .andExpect(jsonPath("$.components.schemas.InterviewSessionResumeMapResponseDto").exists())
            .andExpect(jsonPath("$.components.schemas.InterviewRecordDetailDto").exists())
            .andExpect(jsonPath("$.components.schemas.InterviewRecordTranscriptDto").exists())
            .andExpect(jsonPath("$.components.schemas.InterviewRecordQuestionDto").exists())
            .andExpect(jsonPath("$.components.schemas.InterviewRecordAnalysisDto").exists())
            .andExpect(jsonPath("$.components.schemas.InterviewerProfileDto").exists())
            .andExpect(jsonPath("$.paths['/api/auth/me'].get.security[0].bearerAuth").exists())
            .andExpect(jsonPath("$.components.securitySchemes.bearerAuth").exists())
            .andExpect(jsonPath("$.components.schemas.AuthTokenResponse.description").value("Authentication response containing the bearer token and the authenticated user snapshot"))
            .andExpect(jsonPath("$.components.schemas.HomeResponseDto.description").value("Home payload with the primary daily card, retry queue preview, and learning materials"))
            .andExpect(jsonPath("$.components.schemas.SubmitAnswerRequest.description").value("Answer submission payload for a question attempt"))
    }
}
